const SIGN_IN = 'SIGN_IN';
const LOCATIONS_INDEX = 'LOCATIONS_INDEX';
const GET_LOCATION = 'GET_LOCATION';
const AUTHENTICATE = 'AUTHENTICATE';
export {SIGN_IN, LOCATIONS_INDEX, GET_LOCATION, AUTHENTICATE};
