const SIGN_IN = 'SIGN_IN';
const LOCATIONS_INDEX = 'LOCATIONS_INDEX';
const GET_LOCATION = 'GET_LOCATION';
const AUTHENTICATE = 'AUTHENTICATE';
const LOG_OUT = 'LOG_OUT';
const ALL_SPECIES = 'ALL_SPECIES';
export {SIGN_IN, LOCATIONS_INDEX, GET_LOCATION, AUTHENTICATE, LOG_OUT, ALL_SPECIES};
